package ini.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Comment_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new File_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new KeyValue_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new SectionHeader_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x7f902c7db9de4f86L, 0x8d2e38710197ee79L, 0x4878b309fb52d090L), MetaIdFactory.conceptId(0x7f902c7db9de4f86L, 0x8d2e38710197ee79L, 0x4878b309fb512301L), MetaIdFactory.conceptId(0x7f902c7db9de4f86L, 0x8d2e38710197ee79L, 0x4878b309fb52e040L), MetaIdFactory.conceptId(0x7f902c7db9de4f86L, 0x8d2e38710197ee79L, 0x4878b309fb52d802L)).seal();
}
