package importexport.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.applicationplugins.BaseApplicationPlugin;
import com.intellij.openapi.extensions.PluginId;
import org.jetbrains.annotations.NotNull;

public class Importexport_ApplicationPlugin extends BaseApplicationPlugin {
  private final PluginId myId = PluginId.getId("importexport");

  public Importexport_ApplicationPlugin() {
  }

  @NotNull
  public PluginId getId() {
    return myId;
  }

  public void createGroups() {
    // actions w/o parameters
    addAction(new export_Action());
    addAction(new import_Action());
    // groups
    addGroup(new importexport_ini_ActionGroup(this));
  }
  public void adjustRegularGroups() {
  }
}
