package ini.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int BaseContent = 0;
  public static final int Comment = 1;
  public static final int File = 2;
  public static final int KeyValue = 3;
  public static final int SectionHeader = 4;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x7f902c7db9de4f86L, 0x8d2e38710197ee79L);
    builder.put(0x4878b309fb52cccdL, BaseContent);
    builder.put(0x4878b309fb52d090L, Comment);
    builder.put(0x4878b309fb512301L, File);
    builder.put(0x4878b309fb52e040L, KeyValue);
    builder.put(0x4878b309fb52d802L, SectionHeader);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
